### ISSUE TITLE
Not able to install it via composer in in yii2 project 

### ISSUE THREAD

**Issue by luckyteam143** [coinsbank/coinsbank-php-sdk#1]
Error : 
![error](https://cloud.githubusercontent.com/assets/7627604/26530939/0798c7aa-43fd-11e7-992a-41b5771df13b.png)

 i want to buy/sell , send/receive bitcoins from my website using coinsbank api. i could not found any api reference on Coinsbank panel. i found your plugin for Coinsbank but i am not able to run it. Please help.

TIA

**Comment by coinsbank** [comment]
Just set minimum-stability to dev in your composer.json file

**Comment by luckyteam143** [comment]
- could you please help me to set minimum-stability. here is Composer.json file code


{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": ["yii2", "framework", "basic", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.5",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "dektrium/yii2-user": "^0.9.12",
        "dmstr/yii2-adminlte-asset": "2.*",
		"coinbase/coinbase": "~2.0",
        "blockchain/blockchain": "^1.3"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

**Comment by luckyteam143** [comment]
i updated "minimum-stability": "stable", to "minimum-stability": "dev",  
it is running ..  

Thanks.......
