### ISSUE TITLE
order times

### ISSUE THREAD

**Issue by npomfret** [coinsbank/coinsbank-php-sdk#10]
What timezone are the timestamps in?  Could we have them explicitly in UTC?  For example, in the response to GET /trade:

Instead of 

      "time_create": "2017-06-06 12:40:15.455105",
      "time_update": "2017-06-06 12:40:15.878808",

Could we have:

      "time_create": "2017-06-06T12:40:15.455Z",
      "time_update": "2017-06-06T12:40:15.878Z",

**Comment by coinsbank** [comment]
All dates are in UTC by default. We will update response to include TZ data.

**Comment by npomfret** [comment]
Thanks - that would be a nice improvement.

**Comment by npomfret** [comment]
This seems to have been done - thank you!
