### ISSUE TITLE
order status

### ISSUE THREAD

**Issue by npomfret** [coinsbank/coinsbank-php-sdk#11]
What does the trade status mean?  It's just a number with no description as far as I can see.

How do I get just the open orders?  And How do I get the opposite (i.e. trades that have been executed)?

**Comment by coinsbank** [comment]
Sorry for the late answer. Trade order status have been added to JSON reference to TradeOrder description.
Statuses are the following:
0 - initial
1 - open
2 - closed
3 - cancelled
5 - waiting for Take Profit rate (opposite order has been placed after closing of "parent" order)
6 - waiting for Stop Loss rate (opposite order has been placed after closing of "parent" order)

You may include filters to the filter as array of values. For example 
`GET` /trade/?filter[status][]=2&filter[status][]=3`
will show you closed and cancelled orders
