### ISSUE TITLE
filter example

### ISSUE THREAD

**Issue by npomfret** [coinsbank/coinsbank-php-sdk#14]
Can we get an example of applying a filter to the trades query.  From my web browser I can see this:

`https://coinsbank.com/sapi/trade?filter%5BcurrencyPair%5D%5B%5D=BTCGBP&page=0&pageSize=10&session=x`

Which decodes to:

`https://coinsbank.com/sapi/trade?filter[currencyPair][]=BTCGBP&page=0&pageSize=10&session=x`

Can someone shed some light on what `filter[currencyPair][]=BTCGBP` means.  Why is there an empty array in here?

**Comment by coinsbank** [comment]
You may request trades history for several trading pairs. For example:
`https://coinsbank.com/sapi/trade?filter[currencyPair][]=BTCGBP&filter[currencyPair][]=BTCUSD&filter[currencyPair][]=BTCEUR&filter[currencyPair][]=BTCAUD&page=0&pageSize=10`

**Comment by npomfret** [comment]
Thanks for the reply!

What is the extra `[]` for?  Why is it `filter[currencyPair][]=BTCEUR` and not `filter[currencyPair]=BTCEUR` for example?
