### ISSUE TITLE
unable to delete order

### ISSUE THREAD

**Issue by npomfret** [coinsbank/coinsbank-php-sdk#15]
I'm trying to cancel an order by submitting a `DELETE` at `.../trade/_{orderId}`, but am getting this back:

`{"code":-32602,"message":"Validation failed","fields":{"system":"sapi.error.trade_update_impossible"}} 
`

Pretty sure I had it working.  Has something changed recently?

_EDIT_ I'm also unable to cancel it via your website.

**Comment by coinsbank** [comment]
There was an issue with this particular order, now everything is ok
