### ISSUE TITLE
order book out of sync?

### ISSUE THREAD

**Issue by npomfret** [coinsbank/coinsbank-php-sdk#20]
I recently tried to execute a limit order on a price offered in the order book.  Here's a snippet of the data from my system showing the top of the order book taken from your api:

```
  "market": "BTC/GBP",
  "requestTimestamp": "2017-06-29T09:51:49.097Z",
  "responseTimestamp": "2017-06-29T09:51:49.277Z",
  "bids": [
    {
      "limitPrice": 1939.5000,
      "type": "BID",
      "tradableAmount": 0.93300000,
      "id": "5520591669",
    },
    {
    ...
```
As you can see, the time I made the request was around 09:51:49 (am in UTC).  When I placed my ask limit order at this price it didn't match anything - the price had gone.  However, when I looked at the trades feed I noticed that the price in question had actually gone 9 seconds before: 

    {"tid":39482292,"date":1498729900,"amount":0.933,"price":1939.5,"direction":"ask"}

It looks like the order book was showing a price that was not available because someone had already taken it.

**Comment by npomfret** [comment]
I have another example.  This time I took a snap shot of the order book before and after my trade.  I submit a BID order at the current ASK price.  The order does get matched and yet the price is still available AFTER my order is submitted.  There's definitely something wrong here.

**Comment by coinsbank** [comment]
Orderbooks are changing constantly, they are actual for milliseconds. Before you get orderbook on the client's side it may be obsolete.
For the trades it's the same - we have a lot of connected clients (we believe it's automated bots) producing dozen of requests and placing giant bunches of orders. We don't know logic of these clients, we can just see orderbooks in the same state as you.

**Comment by npomfret** [comment]
Thanks for the reply, but can you take another look.  This market is very quiet and not as you've described at all.  I really think you have a problem here.

[This](https://gist.github.com/npomfret/c28c6b0cdad00ad01378d72412084d6e) order book for example, has the same price at the top of the order book both both bid and ask.  If your api was working properly this state should not arrive because the 2 orders should have matched.

**Comment by npomfret** [comment]
And [here](https://gist.github.com/npomfret/0a17d166119a84dad511751d866aae2d), the bid and ask are at the same price (_2133.65145_).  How is this possible?

**Comment by ozkanerdogmus** [comment]
Hi, npomfret

Did you find an solution for this problem? Thank you

**Comment by coinsbank** [comment]
@ozkanerdogmus @npomfret Take a look for new websocket API in trading interface, it faster than REST API

**Comment by npomfret** [comment]
@ozkanerdogmus no solution, I stopped trading with them as I don't trust their exchange technology enough.

**Comment by ozkanerdogmus** [comment]
Yes you right. I had lots of problems too.. There are big problems with market structures and trading informations.

**Comment by ozkanerdogmus** [comment]
@coinsbank i will look at your new API too. How can I find it? Where is?

**Comment by ozkanerdogmus** [comment]
@coinsbank waiting for answer?
