### ISSUE TITLE
$apiKey = ''; $apiSecret = '' Not Able to find API_Secret from Coisbank account.

### ISSUE THREAD

**Issue by luckyteam143** [coinsbank/coinsbank-php-sdk#3]
i got the api_key from te Coinsbank Account . what will be the api_secret .... 

TIA.

**Comment by luckyteam143** [comment]
I found it. 
In Consbank api- scan QR Code in order to get Api Secret..


Thanks

**Comment by coinsbank** [comment]
After creating API key it will appear in keys list. Click on the "QR code" link to view secret part of the key, it will be visible just below the QR code.
