### ISSUE TITLE
"message":"sapi.error.auth.invalid_api_key"

### ISSUE THREAD

**Issue by luckyteam143** [coinsbank/coinsbank-php-sdk#4]
I am trying to run below code 
///////Head Auth //////
$contextAuthorized = new CoinsbankApiContext($Key, $Secret, [], CoinsbankApiContext::MODE_SANDBOX);
$headApiAuth = new CoinsbankHead($contextAuthorized);
$response = $headApiAuth->getData();

**Getting Error:**

Coinsbank\Transport\CoinsbankResponse Object ( [body:protected] => {"code":-33108,"message":"sapi.error.auth.invalid_api_key"} [headers:protected] => Array ( [Date] => Array ( [0] => Wed, 31 May 2017 11:07:40 GMT ) [Content-Type] => Array ( [0] => application/json ) [Transfer-Encoding] => Array ( [0] => chunked ) [Connection] => Array ( [0] => keep-alive ) [Set-Cookie] => Array ( [0] => __cfduid=d2c7229d392dc63c13d499cb8481ce9241496228860; expires=Thu, 31-May-18 11:07:40 GMT; path=/; domain=.coinsbank.com; HttpOnly ) [Strict-Transport-Security] => Array ( [0] => max-age=15552000; includeSubDomains ) [X-Content-Type-Options] => Array ( [0] => nosniff ) [Server] => Array ( [0] => cloudflare-nginx ) [CF-RAY] => Array ( [0] => 367978887b662f0b-DEL ) ) [httpResponseCode:protected] => 403 ) 

////////// Wallet ////////
$contextAuthorized = new CoinsbankApiContext($Key, $Secret, [], CoinsbankApiContext::MODE_SANDBOX)
$walletApi = new CoinsbankWallet($contextAuthorized);
$response = $walletApi->getList();

**Error :** 

syntax error, unexpected '$walletApi' (T_VARIABLE)

is this authentication Error. I cross checked the Api Key and Secret .  

TIA

**Comment by coinsbank** [comment]
You have no semicolon after 
`$contextAuthorized = new CoinsbankApiContext($Key, $Secret, [], CoinsbankApiContext::MODE_SANDBOX)`

Please also check if the key and secret was generated on testing or production system. Maybe you are trying to use production key for testing server?
