### ISSUE TITLE
api spec?

### ISSUE THREAD

**Issue by npomfret** [coinsbank/coinsbank-php-sdk#5]
@coinsbank is there an api spec somewhere?  I'm trying to implement this in another language and reverse engineering your php is a bit tricky.

I can see some stuff in coinsbank-sapi.json... but what about stuff like the http headers?

**Comment by coinsbank** [comment]
@npomfret spec available at https://github.com/coinsbank/coinsbank-php-sdk/blob/master/reference/coinsbank-sapi.json (reference folder in project root) in swagger 2.0 format

**Comment by npomfret** [comment]
What for example does this mean though?

    {
      "name": "Signature",
      "in": "header",
      "description": "Signature generated from request data",
      "required": true,
      "schema": {
        "type": "string"
      }
    }

**Comment by npomfret** [comment]
@coinsbank what is the Signature please?  The swagger spec just says "string".
