### ISSUE TITLE
what is the Signature header?

### ISSUE THREAD

**Issue by npomfret** [coinsbank/coinsbank-php-sdk#7]
The spec doesn't say how to construct the `Signature` header.  Are there any docs that explain what it is?

An example would be good.  For example, just a simple GET for /wallet.  What would that look like?

**Comment by npomfret** [comment]
Thanks for the [curl](https://github.com/coinsbank/coinsbank-php-sdk/blob/master/examples/example-curl-new-merchant-invoice.sh) example.  That's helpful.

**Comment by coinsbank** [comment]
You're welcome. If you will have any questions regarding requests signatures, please contact dev@coinsbank.com. Documentation also will be improved soon.
