### ISSUE TITLE
order book

### ISSUE THREAD

**Issue by npomfret** [coinsbank/coinsbank-php-sdk#9]
I can't see a way to get the order book listed in the api.  I notice by browser hits `bitcoincharts/orderbook/{currencyPair}` and `public/ticker`.  Are these what I need to use?  Or is there a more _official_ method?

Also, a list of trades that have happened would be useful.

**Comment by coinsbank** [comment]
Class CoinsbankApi from SDK uses bitcoincharts/trades and bitcoincharts/orderbook endpoints, so it's official methods to get history and orderbook. Specs are describing only /sapi/* endpoints and not covers other public methods. We will improve docs accordingly.
You may use bitcoincharts/* URLs, they will not change in a future.
